# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171217_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(help_text="User's address.", null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Address'),
        ),
    ]
